### ISSUE TITLE
Problem with PrimaryKey when create new task and save

### ISSUE THREAD

**Issue by toantran-ea** [CasterIO/Tasko#1]
```
Process: com.donnfelker.tasko, PID: 27019
io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 
at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:636)
at io.realm.internal.Table.addEmptyRow(Table.java:360)
at io.realm.Realm.createObject(Realm.java:661)
at com.donnfelker.tasko.fragments.NewTaskFragment.addTask(NewTaskFragment.java:116)
at com.donnfelker.tasko.fragments.NewTaskFragment.onAddClick(NewTaskFragment.java:90)
at com.donnfelker.tasko.fragments.NewTaskFragment$$ViewBinder$1.doClick(NewTaskFragment$$ViewBinder.java:18)
at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
at android.view.View.performClick(View.java:4780)
at android.view.View$PerformClick.run(View.java:19866)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Hi, I tried with branch `forecastio`, when adding new task, this issue happened.
I found that with `CurrentConditionService`, when inserting new task into Realm, we did not set unique UUID for that task.

Please check the PR here: https://github.com/CasterIO/Tasko/pull/2

**Comment by toantran-ea** [comment]
@donnfelker Thanks for merging the PR. This issue should be closed then ;)
